// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SiteConfig = XP.SiteConfig;

declare global {
  namespace XP {
    interface SiteConfig {
      /**
       * Fathom site key
       */
      fathomSiteKey: string;

      /**
       * Tracking type – SPA modes
       */
      spa: "auto" | "history" | "hash";

      /**
       * Honor Do Not Track
       */
      honorDnt: boolean;

      /**
       * Ignore canonicals
       */
      ignoreCanonical: boolean;

      /**
       * Automatically add script to page
       */
      automaticallyAddToPage: boolean;
    }
  }
}
